version: '3'
services:
  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: '69'
      SECRET: 'replace-with-random-value'
      ADMIN_EMAIL: 'anongbarry@gmail.com'
      ADMIN_PASSWORD: '1234'
      DB_CLIENT: 'sqlite3'
      DB_FILENAME: '/directus/database/bookerdb.db'
      WEBSOCKETS_ENABLED: true